version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./src/Web/API/Dockerfile
    image: saphyre-api
    ports:
      - "5000:5000"
    env_file: .env
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5000

  ui:
    build:
      context: .
      dockerfile: ./src/Web/UI/Dockerfile
    image: saphyre-ui
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - api
