version: '3.9'

services:
  api:
    image: saphyre-api
    build:
      context: .
      dockerfile: Dockerfile
      target: api-runtime
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  ui:
    image: saphyre-ui
    build:
      context: .
      dockerfile: Dockerfile
      target: ui-runtime
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - api
